### ISSUE TITLE
Support for tagging like vX.X.x

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [outbrain/ci-friendly-flatten-maven-plugin#13]
I try to use tagging like i.e. spring boot use v1.0.0

Problem starts when tag is configured as v${project.version}
```
[INFO] --- ci-friendly-flatten-maven-plugin:1.0.9:version (default-cli) @ qa-core ---
[INFO] Current version:v8.0.1
[INFO] revision without prefix:v8.0.1
````
revision is not strip out of prefix because of implementation assume `-` between prefix and version
https://github.com/outbrain/ci-friendly-flatten-maven-plugin/blob/aa54864d30ca4cb0f5ee699b95e59deb3e083100/src/main/java/com/outbrain/ci/friendly/flatten/maven/plugin/VersionMojo.java#L133

maybe separated property prefix should be introduced?

**Comment by ayoukhananov** [comment]
@piotrwielgolaski-tomtom Just released 1.0.10 version .
You can pass prefix as part of the configuration 
<configuration>
              <prefixRegex>v</prefixRegex>
            </configuration>
