### ISSUE TITLE
Newer release are not there in central repo

### ISSUE THREAD

**Issue by pmverma** [outbrain/ci-friendly-flatten-maven-plugin#40]
You can notice that last version was 1.0.3
https://repo1.maven.org/maven2/com/outbrain/swinfra/ci-friendly-maven-plugin/

Is there any plan to publish newer version?

**Comment by pmverma** [comment]
Never mind.
I notice that artifact name has changed

**Comment by ayoukhananov** [comment]
@pmverma 
The correct one is :
https://repo1.maven.org/maven2/com/outbrain/swinfra/ci-friendly-flatten-maven-plugin/

If you still need the requirement/suggestions or missing functionality, please open an issue or PR .
Thanks Avi Y
