### ISSUE TITLE
[BUG]: Problem with working with maven shaded

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [outbrain/ci-friendly-flatten-maven-plugin#42]
### Description of the bug

There is issue with working with this plugin when maven-shade plugin is used

Details and fix in flatten plugin is here https://github.com/mojohaus/flatten-maven-plugin/issues/100

### Steps To Reproduce

Use shade plugin and check if in dependency-reduced-pom.xml ${revision} is replaced

### Additional Information

it seems that we lack of one extra call around https://github.com/outbrain/ci-friendly-flatten-maven-plugin/blob/main/src/main/java/com/outbrain/ci/friendly/flatten/maven/plugin/FlattenMojo.java#L57
```
this.project.setOriginalModel( flattenedPom );
```

https://github.com/mojohaus/flatten-maven-plugin/pull/281/files#diff-9f8ec1d13bc75e576b6c21b96d277373eb856d5465ef87ef675a983b3ade36beR425

**Comment by ayoukhananov** [comment]
Thanks @piotrwielgolaski-tomtom 
We will look into it .

**Comment by ayoukhananov** [comment]
@piotrwielgolaski-tomtom 
Can you please create a Pull Request with this change ?

**Comment by piotrwielgolaski-tomtom** [comment]
@ayoukhananov I created the simplest fix, tested in my scenario and it works

**Comment by ayoukhananov** [comment]
@piotrwielgolaski-tomtom We have few junit tests and lack of integration tests , this is the main reason it takes so long.

**Comment by ayoukhananov** [comment]
@piotrwielgolaski-tomtom Was released with 1.0.16
